### ISSUE TITLE
X and Y

### ISSUE THREAD

**Issue by Khotul** [towerstorm/game#1]
Hello. I love tower defense games, but I'm not very experienced in programming. I wanted to create my own map, so I created .png file and using a certain program drew it, and saved in assets/img/maps. Then I've copied deep-space-collisions and renamed it to name of my map. But now I have to change X and Y values everywhere so it will fit my map, but I don't know how to or what to use to calculate positions. Could anyone explain me how to do it?

**Comment by timjrobinson** [comment]
So the X and Y values correspond to the "tiles" on the map. Each tile is 48 pixels in size. Tile 0,0 is the very top left corner of the map. Tile 1,0 is the tile 48px to the right and 0px down. Tile 2,0 is the tile 96px to the right and 0px down. Tile 0,1 is the tile along the left hand edge and 48px down. 

You also have to set the width and height of your map in "tiles". This width and height is only of the playing area of the game, and the game assumes that the play area is in the center of the map. So if your new map is 1000px wide, 1000px tall, but it has a border of 20px all around it (for adding trees or space or something for decoration), then the actual play area will be 960px by 960px and you should set the width and height both to 20 (because each tile is 48px and 48 * 20 = 960). Does this make sense?

Let me know if you have any more questions about map editing, I'm excited to see what you've come up with!
