### ISSUE TITLE
Ending game because someone started it but never joined it

### ISSUE THREAD

**Issue by Khotul** [towerstorm/game#2]
When I try to create a game, something like this shows up.
![issue2a](https://user-images.githubusercontent.com/38328195/40554931-aaa17bf6-6047-11e8-8d4e-025175ca154a.png)
Errors that shows up on web browser console:
![issue2b](https://user-images.githubusercontent.com/38328195/40555011-e82f556a-6047-11e8-92ad-1519c67313d4.png)
In cmd only this shows up:
![issue2c](https://user-images.githubusercontent.com/38328195/40555055-21f43bda-6048-11e8-82af-9c18deb894d9.png)

Things worth mentioning:
-I think it has something to do with "/img/maps not found", but the folder is here
-I'm running both RethinkDB and server on Windows 10. I tried to do it on Ubuntu, however I had many problems with virtual machine, so I decided to give up and try running it on Windows.
-I'm using cross-env, which allows me to use NODE_ENV=development/production on Windows
-I had to change localhost to 127.0.0.1 in netconfig.js, because I had error "Unable to connect to RethinkDB"
-Sandbox freezes at loading screen on 100%
-Running server on Linux doesn't solve my problem
-Also this problem keeps appearing, I don't think it's related to my problem, but it's still worth mentioning
![issue2d](https://user-images.githubusercontent.com/38328195/40555484-9761733c-6049-11e8-8e13-036ea8eb06cf.png)
I always loved tower defense games, and I've played TowerStorm few years ago, once I even emailed you about desync problem, but my english was horrible at that time (it still is) and I think you most probably didn't know what I was talking about. Please help me solve this problem, I really want to play TowerStorm again with my friends. I can't play on your website, because I'm stuck at "Game creating, please wait...".

**Comment by timjrobinson** [comment]
Sorry about taking so long to get back to you on this. 

It seems like the game isn't initializing your user correctly, that's what's causing those 403 errors when accessing /user at the beginning. When you load the main menu the game tries to create a temporary user and then uses that for game creation / joining etc. It then saves the user info out to a cookie. Even the sandbox uses this user. 

I've seen this happen where I've opened tower storm, which created a user cookie, then wiped the database, then gone back to tower storm. When doing this the browser tries to use the old user cookie which the server can't find in the database and so it throws 403 errors when trying to access /user. 

Could you try clearing your browser cookies or opening in a private window and see if the problem persists. 

It may also be because you're using `localhost` as the domain name and so the cookie isn't being created properly because of this. You could try setting the environment variable `HOSTNAME` to any domain you want (try `ts.devel`) then open the file `C:\Windows\System32\drivers\etc\hosts` and add the string `127.0.0.1 ts.devel` to it, then navigate to `http://ts.devel:8080/` to play.

**Comment by timjrobinson** [comment]
I've also brought the official server back online. The DB Crashed because it ran out of space (forgot to add logrotation to the towerstorm log file).

**Comment by timjrobinson** [comment]
I just found the root cause of this bug when I was playing around with Tower Storm today. 

It's because the cookie being generated by lobby service doesn't have the right hostname, and so it creates a cookie for your user but the game can't read it and throws forbidden errors. I'm creating a patch that adds a warning about this now.
